name: Build

on:
  workflow_dispatch:
  push:
    branches: [ main, staging ]
  pull_request:
    branches: [ main, staging ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install Dependencies
      run: |
          sudo apt install -y libopenmpi-dev openmpi-bin libopenblas-serial-dev
    - name: Build Wave Solver
      run: |
        cd libparanumal/solvers/wave
        make -j `nproc` verbose=true
      env:
        LIBP_COVERAGE: 1
    - name: Test Wave Solver
      run: |
        cd libparanumal/solvers/wave
        make test
        bash <(curl --no-buffer -s https://codecov.io/bash) -x gcov
      env:
        LIBP_COVERAGE: 1
